wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1658480462
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 19
      4: 3.9.13
      5: 0.12.21
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 64
buffer_size:
  desc: null
  value: 10000
epsilon:
  desc: null
  value: 0.9
epsilon_decay:
  desc: null
  value: 0.99
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 1.0e-06
min_epsilon:
  desc: null
  value: 0.01
num_episodes:
  desc: null
  value: 50000
tau:
  desc: null
  value: 0.001
